# Etude De marché 
Une enteprise francasie d'agroalimentaire specialisee dans le poulet souhaite se developper a l'international. La strategie mise sur l'exportation, Preferable dans un premier temps a une production sur place.
il faudra donc cibler les pays les plus enclins a importer du poulet.
Pour identifier ce groupe de pays, on poura etudier leurs indicateur de demographies et regimes alimentaires grace aux données  mise a disposition par la FAO

In [2]:
pip install pca

Requirement already satisfied: pca in c:\users\zolboy\anaconda3\lib\site-packages (1.6.2)
Requirement already satisfied: matplotlib in c:\users\zolboy\anaconda3\lib\site-packages (from pca) (3.4.3)
Requirement already satisfied: scipy in c:\users\zolboy\anaconda3\lib\site-packages (from pca) (1.7.1)
Requirement already satisfied: wget in c:\users\zolboy\anaconda3\lib\site-packages (from pca) (3.2)
Requirement already satisfied: sklearn in c:\users\zolboy\anaconda3\lib\site-packages (from pca) (0.0)
Requirement already satisfied: numpy in c:\users\zolboy\anaconda3\lib\site-packages (from pca) (1.20.3)
Requirement already satisfied: tqdm in c:\users\zolboy\anaconda3\lib\site-packages (from pca) (4.62.3)
Requirement already satisfied: pandas in c:\users\zolboy\anaconda3\lib\site-packages (from pca) (1.3.4)
Requirement already satisfied: colourmap in c:\users\zolboy\anaconda3\lib\site-packages (from pca) (0.1.1)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\zolboy\anaconda3\lib\site-packages (from matplotlib->pca) (1.3.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\zolboy\anaconda3\lib\site-packages (from matplotlib->pca) (2.8.2)
Requirement already satisfied: pillow>=6.2.0 in c:\users\zolboy\anaconda3\lib\site-packages (from matplotlib->pca) (8.4.0)
Requirement already satisfied: cycler>=0.10 in c:\users\zolboy\anaconda3\lib\site-packages (from matplotlib->pca) (0.10.0)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\zolboy\anaconda3\lib\site-packages (from matplotlib->pca) (3.0.4)
Requirement already satisfied: six in c:\users\zolboy\anaconda3\lib\site-packages (from cycler>=0.10->matplotlib->pca) (1.16.0)
Requirement already satisfied: pytz>=2017.3 in c:\users\zolboy\anaconda3\lib\site-packages (from pandas->pca) (2021.3)
Requirement already satisfied: scikit-learn in c:\users\zolboy\anaconda3\lib\site-packages (from sklearn->pca) (0.24.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\zolboy\anaconda3\lib\site-packages (from scikit-learn->sklearn->pca) (2.2.0)
Requirement already satisfied: joblib>=0.11 in c:\users\zolboy\anaconda3\lib\site-packages (from scikit-learn->sklearn->pca) (1.1.0)
Requirement already satisfied: colorama in c:\users\zolboy\anaconda3\lib\site-packages (from tqdm->pca) (0.4.4)
Note: you may need to restart the kernel to use updated packages.

In [3]:
# Librairies
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
import seaborn as sns
import sklearn as sk
import scipy as sp
import pca as pca

In [5]:
sns.set(# Styles Seaborn
    style = 'whitegrid',
    context = 'notebook',
    palette = 'Paired',
    rc = {'figure.figsize':(8,5)}
)

In [6]:
# Couleurs : 
red_a400 = '#ff1744'
indigo_a100 = '#8c9eff'
indigo_a400 = '#3d5afe'
indigo_a700 = '#304ffe'
bluegrey_900 = '#263238'
teal_a400 = '#1de9b6'
purple_a400 = '#d500f9'
yellow_a400 = '#ffea00'
bluegrey_900 = '#263238'
palette_5 = [teal_a400, indigo_a400, red_a400, yellow_a400, purple_a400]

In [7]:
#Adress D'enrigestrement des graphiques
url_fig = 'graphiques/'

## Preparation des Data
### Exploration

In [12]:
url = 'https://raw.githubusercontent.com/bbouya/Data_Analyst/main/etude_marche/sources/fao_'

# Liste des colonnes non nécessaires qu'on supprimera à l'importation
drop_columns = ['Domain Code', 'Element Code', 'Item Code', 'Flag', 'Flag Description', 'Year Code']

## Nouveaux Bilans Alimentaires 
Les disponibilites alimentaires par jour et par habitant. en termes de proteines et de calories. On dispose aussi pour chaque apport de la disponibilité des produit animaux uniquement.

In [13]:
food = pd.read_csv(url + 'new-food-balances.csv').drop(drop_columns, axis=1) 
food

,Domain,Area Code,Area,Element,Item,Year,Unit,Value
0,New Food Balances,2,Afghanistan,Food supply (kcal/capita/day),Grand Total,2018,kcal/capita/day,2040.00
1,New Food Balances,2,Afghanistan,Protein supply quantity (g/capita/day),Grand Total,2018,g/capita/day,55.52
2,New Food Balances,2,Afghanistan,Food supply (kcal/capita/day),Animal Products,2018,kcal/capita/day,191.00
3,New Food Balances,2,Afghanistan,Protein supply quantity (g/capita/day),Animal Products,2018,g/capita/day,10.79
4,New Food Balances,3,Albania,Food supply (kcal/capita/day),Grand Total,2018,kcal/capita/day,3360.00
...,...,...,...,...,...,...,...,...
687,New Food Balances,251,Zambia,Protein supply quantity (g/capita/day),Animal Products,2018,g/capita/day,13.70
688,New Food Balances,181,Zimbabwe,Food supply (kcal/capita/day),Grand Total,2018,kcal/capita/day,1908.00
689,New Food Balances,181,Zimbabwe,Protein supply quantity (g/capita/day),Grand Total,2018,g/capita/day,44.15
690,New Food Balances,181,Zimbabwe,Food supply (kcal/capita/day),Animal Products,2018,kcal/capita/day,159.00
691,New Food Balances,181,Zimbabwe,Protein supply quantity (g/capita/day),Animal Products,2018,g/capita/day,11.59

In [14]:
food.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 692 entries, 0 to 691
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Domain     692 non-null    object
 1   Area Code  692 non-null    int64
 2   Area       692 non-null    object
 3   Element    692 non-null    object
 4   Item       692 non-null    object
 5   Year       692 non-null    int64
 6   Unit       692 non-null    object
 7   Value      692 non-null    float64
dtypes: float64(1), int64(2), object(5)
memory usage: 43.4+ KB

## Elevage Primaire
En tonnes, La production, l'importation et l'exporation de poulet en 2018

In [15]:
livestock = pd.read_csv(url + 'livestock-primary.csv').drop(drop_columns, axis=1) # Élevage primaire
livestock

,Domain,Area Code,Area,Element,Item,Year,Unit,Value
0,Livestock Primary,2,Afghanistan,Production,"Meat, chicken",2018,tonnes,28850
1,Livestock Primary,2,Afghanistan,Import Quantity,"Meat, chicken",2018,tonnes,23913
2,Livestock Primary,2,Afghanistan,Export Quantity,"Meat, chicken",2018,tonnes,154
3,Livestock Primary,3,Albania,Production,"Meat, chicken",2018,tonnes,15587
4,Livestock Primary,3,Albania,Import Quantity,"Meat, chicken",2018,tonnes,11588
...,...,...,...,...,...,...,...,...
544,Livestock Primary,251,Zambia,Import Quantity,"Meat, chicken",2018,tonnes,10540
545,Livestock Primary,251,Zambia,Export Quantity,"Meat, chicken",2018,tonnes,1387
546,Livestock Primary,181,Zimbabwe,Production,"Meat, chicken",2018,tonnes,65837
547,Livestock Primary,181,Zimbabwe,Import Quantity,"Meat, chicken",2018,tonnes,3758
548,Livestock Primary,181,Zimbabwe,Protein supply quantity (g/capita/day),"Meat, chicken",2018,g/capita/day,2

In [16]:
livestock.info() # Aucune valeur manquante

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 549 entries, 0 to 548
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Domain     549 non-null    object
 1   Area Code  549 non-null    int64
 2   Area       549 non-null    object
 3   Element    549 non-null    object
 4   Item       549 non-null    object
 5   Year       549 non-null    int64
 6   Unit       549 non-null    object
 7   Value      549 non-null    int64
dtypes: int64(3), object(5)
memory usage: 34.4+ KB

## Series temporelles annuelles
Le nombre d'habitants en 2008 et 2018

In [17]:
population = pd.read_csv(url + 'annual-population.csv').drop(drop_columns, axis=1) # Séries temporelles annuelles
population

,Domain,Area Code,Area,Element,Item,Year,Unit,Value,Note
0,Annual population,2,Afghanistan,Total Population - Both sexes,Population - Est. & Proj.,2008,1000 persons,27722.276,NaN
1,Annual population,2,Afghanistan,Total Population - Both sexes,Population - Est. & Proj.,2018,1000 persons,37171.921,NaN
2,Annual population,3,Albania,Total Population - Both sexes,Population - Est. & Proj.,2008,1000 persons,3002.678,NaN
3,Annual population,3,Albania,Total Population - Both sexes,Population - Est. & Proj.,2018,1000 persons,2882.740,NaN
4,Annual population,4,Algeria,Total Population - Both sexes,Population - Est. & Proj.,2008,1000 persons,34730.608,NaN
...,...,...,...,...,...,...,...,...,...
463,Annual population,249,Yemen,Total Population - Both sexes,Population - Est. & Proj.,2018,1000 persons,28498.683,NaN
464,Annual population,251,Zambia,Total Population - Both sexes,Population - Est. & Proj.,2008,1000 persons,12848.530,NaN
465,Annual population,251,Zambia,Total Population - Both sexes,Population - Est. & Proj.,2018,1000 persons,17351.708,NaN
466,Annual population,181,Zimbabwe,Total Population - Both sexes,Population - Est. & Proj.,2008,1000 persons,12379.549,NaN
467,Annual population,181,Zimbabwe,Total Population - Both sexes,Population - Est. & Proj.,2018,1000 persons,14438.802,NaN

In [18]:
population.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 468 entries, 0 to 467
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Domain     468 non-null    object
 1   Area Code  468 non-null    int64
 2   Area       468 non-null    object
 3   Element    468 non-null    object
 4   Item       468 non-null    object
 5   Year       468 non-null    int64
 6   Unit       468 non-null    object
 7   Value      468 non-null    float64
 8   Note       8 non-null      object
dtypes: float64(1), int64(2), object(6)
memory usage: 33.0+ KB

#  Data de la securite alimentaire
Le PIB en 2008 et 2018

In [19]:
security = pd.read_csv(url + 'security-indicators.csv').drop(drop_columns, axis=1) # Données de la sécurité alimentaire
security

,Domain,Area Code,Area,Element,Item,Year,Unit,Value,Note
0,Suite of Food Security Indicators,2,Afghanistan,Value,"Gross domestic product per capita, PPP, dissem...",2008,I$,1587.80,NaN
1,Suite of Food Security Indicators,2,Afghanistan,Value,"Gross domestic product per capita, PPP, dissem...",2018,I$,2190.20,NaN
2,Suite of Food Security Indicators,2,Afghanistan,Value,Political stability and absence of violence/te...,2008,index,-2.69,NaN
3,Suite of Food Security Indicators,2,Afghanistan,Value,Political stability and absence of violence/te...,2018,index,-2.75,NaN
4,Suite of Food Security Indicators,3,Albania,Value,"Gross domestic product per capita, PPP, dissem...",2008,I$,10119.10,NaN
...,...,...,...,...,...,...,...,...,...
759,Suite of Food Security Indicators,251,Zambia,Value,Political stability and absence of violence/te...,2018,index,0.14,NaN
760,Suite of Food Security Indicators,181,Zimbabwe,Value,"Gross domestic product per capita, PPP, dissem...",2008,I$,1739.20,NaN
761,Suite of Food Security Indicators,181,Zimbabwe,Value,"Gross domestic product per capita, PPP, dissem...",2018,I$,3130.00,NaN
762,Suite of Food Security Indicators,181,Zimbabwe,Value,Political stability and absence of violence/te...,2008,index,-1.21,NaN
763,Suite of Food Security Indicators,181,Zimbabwe,Value,Political stability and absence of violence/te...,2018,index,-0.71,NaN

In [22]:
def doublons(df):
    print(len(df) - len(df.drop_duplicates()), 'doublons')

for i in [food, livestock, population, security]:
    doublons(i)

0 doublons
0 doublons
0 doublons
0 doublons

## Concatenation et pivot
Les 4 dataframe ayant les memes noms de variables, on commence par les concatener.

In [23]:
data = pd.concat([food,livestock,population,security]) # Concatenation
data

,Domain,Area Code,Area,Element,Item,Year,Unit,Value,Note
0,New Food Balances,2,Afghanistan,Food supply (kcal/capita/day),Grand Total,2018,kcal/capita/day,2040.00,NaN
1,New Food Balances,2,Afghanistan,Protein supply quantity (g/capita/day),Grand Total,2018,g/capita/day,55.52,NaN
2,New Food Balances,2,Afghanistan,Food supply (kcal/capita/day),Animal Products,2018,kcal/capita/day,191.00,NaN
3,New Food Balances,2,Afghanistan,Protein supply quantity (g/capita/day),Animal Products,2018,g/capita/day,10.79,NaN
4,New Food Balances,3,Albania,Food supply (kcal/capita/day),Grand Total,2018,kcal/capita/day,3360.00,NaN
...,...,...,...,...,...,...,...,...,...
759,Suite of Food Security Indicators,251,Zambia,Value,Political stability and absence of violence/te...,2018,index,0.14,NaN
760,Suite of Food Security Indicators,181,Zimbabwe,Value,"Gross domestic product per capita, PPP, dissem...",2008,I$,1739.20,NaN
761,Suite of Food Security Indicators,181,Zimbabwe,Value,"Gross domestic product per capita, PPP, dissem...",2018,I$,3130.00,NaN
762,Suite of Food Security Indicators,181,Zimbabwe,Value,Political stability and absence of violence/te...,2008,index,-1.21,NaN
763,Suite of Food Security Indicators,181,Zimbabwe,Value,Political stability and absence of violence/te...,2018,index,-0.71,NaN

In [24]:
# Table pivot
data = data.pivot_table(index='Area', values='Value', columns=['Element', 'Item', 'Year']).reset_index()
data

Element                       Area Export Quantity  \
Item                                 Meat, chicken
Year                                          2018
0                      Afghanistan           154.0
1                          Albania             NaN
2                          Algeria             NaN
3                   American Samoa             NaN
4                          Andorra             NaN
..                             ...             ...
233      Wallis and Futuna Islands             NaN
234                 Western Sahara             NaN
235                          Yemen             NaN
236                         Zambia          1387.0
237                       Zimbabwe             NaN

Element Food supply (kcal/capita/day)             Import Quantity  \
Item                  Animal Products Grand Total   Meat, chicken
Year                             2018        2018            2018
0                               191.0      2040.0         23913.0
1                              1003.0      3360.0         11588.0
2                               390.0      3322.0            27.0
3                                 NaN         NaN             NaN
4                                 NaN         NaN             NaN
..                                ...         ...             ...
233                               NaN         NaN             NaN
234                               NaN         NaN             NaN
235                             142.0      2154.0         95992.0
236                             159.0      2002.0         10540.0
237                             159.0      1908.0          3758.0

Element    Production Protein supply quantity (g/capita/day)              \
Item    Meat, chicken                        Animal Products Grand Total
Year             2018                                   2018        2018
0             28850.0                                  10.79       55.52
1             15587.0                                  61.75      115.74
2            278279.0                                  24.73       91.83
3                 NaN                                    NaN         NaN
4                 NaN                                    NaN         NaN
..                ...                                    ...         ...
233               NaN                                    NaN         NaN
234               NaN                                    NaN         NaN
235          179768.0                                  10.38       54.52
236           49487.0                                  13.70       60.53
237           65837.0                                  11.59       44.15

Element               Total Population - Both sexes             \
Item    Meat, chicken     Population - Est. & Proj.
Year             2018                          2008       2018
0                 NaN                     27722.276  37171.921
1                 3.0                      3002.678   2882.740
2                 2.0                     34730.608  42228.408
3                 NaN                        57.492     55.465
4                 NaN                        83.862     77.006
..                ...                           ...        ...
233               NaN                        13.578     11.661
234               NaN                       468.633    567.402
235               NaN                     21892.146  28498.683
236               NaN                     12848.530  17351.708
237               2.0                     12379.549  14438.802

Element                                                                                 Value  \
Item    Gross domestic product per capita, PPP, dissemination (constant 2011 international $)
Year                                                                                     2008
0                                                   1587.8
1                                                  10119.1
2                                                  10625.0
3                                                      NaN
4                                                      NaN
..                                                     ...
233                                                    NaN
234                                                    NaN
235                                                    NaN
236                                                 2747.4
237                                                 1739.2

Element           \
Item
Year        2018
0         2190.2
1        13601.3
2        11479.5
3            NaN
4            NaN
..           ...
233          NaN
234          NaN
235          NaN
236       3521.5
237       3130.0

Element
Item    Political stability and absence of violence/terrorism (index)
Year                                                             2008  2018
0                                                    -2.69            -2.75
1                                                    -0.03             0.38
2                                                    -1.09            -0.79
3                                                     0.98             1.21
4                                                     1.34             1.43
..                                                     ...              ...
233                                                    NaN              NaN
234                                                    NaN              NaN
235                                                  -2.01            -3.00
236                                                   0.47             0.14
237                                                  -1.21            -0.71

[238 rows x 15 columns]

On cree une nouvelle dataframe pour n'y conserver que les variable utiles, et de nouvelles:
 * la croissance de la population entre les 2 années de reference
 * * le ratio de proteines d'origine animale dans de la disponibilite alimentaire proteique

In [25]:
# Abbréviations du multiIndex
export, imports, production, chicken, kcal, prot, pop, pop2, animal, total, secu, pib, stable = 'Export Quantity', 'Import Quantity', 'Production', 'Meat, chicken', 'Food supply (kcal/capita/day)', 'Protein supply quantity (g/capita/day)', 'Total Population - Both sexes', 'Population - Est. & Proj.', 'Animal Products', 'Grand Total', 'Value', 'Gross domestic product per capita, PPP, dissemination (constant 2011 international $)', 'Political stability and absence of violence/terrorism (index)'
annee_a, annee_b = 2008, 2018

# Nouvelles variables
df = pd.DataFrame()
df['pays'] = data['Area']
df['dispo_calories'] = data[kcal][total][annee_b]
df['dispo_proteines'] = data[prot][total][annee_b]
df['ratio_proteines_animales'] = data[prot][animal][annee_b] / data[prot][total][annee_b]
df['population'] = data[pop][pop2][annee_b] / 1000 # Millions d'habitants
df['population_croissance'] = data[pop][pop2][annee_b] / data[pop][pop2][annee_a]
df['pib'] = data[secu][pib][annee_b]
df['ppa'] = df['pib'] / (df['population'] * 10**6) # PIB / habitant
df['pib_croissance'] = data[secu][pib][annee_b] / data[secu][pib][annee_a]
df['poulet_import-export'] = data[imports][chicken][annee_b] / data[export][chicken][annee_b]
df

,pays,dispo_calories,dispo_proteines,ratio_proteines_animales,population,population_croissance,pib,ppa,pib_croissance,poulet_import-export
0,Afghanistan,2040.0,55.52,0.194344,37.171921,1.340868,2190.2,0.000059,1.379393,155.279221
1,Albania,3360.0,115.74,0.533523,2.882740,0.960056,13601.3,0.004718,1.344122,NaN
2,Algeria,3322.0,91.83,0.269302,42.228408,1.215885,11479.5,0.000272,1.080424,NaN
3,American Samoa,NaN,NaN,NaN,0.055465,0.964743,NaN,NaN,NaN,NaN
4,Andorra,NaN,NaN,NaN,0.077006,0.918247,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
233,Wallis and Futuna Islands,NaN,NaN,NaN,0.011661,0.858816,NaN,NaN,NaN,NaN
234,Western Sahara,NaN,NaN,NaN,0.567402,1.210760,NaN,NaN,NaN,NaN
235,Yemen,2154.0,54.52,0.190389,28.498683,1.301777,NaN,NaN,NaN,NaN
236,Zambia,2002.0,60.53,0.226334,17.351708,1.350482,3521.5,0.000203,1.281757,7.599135
237,Zimbabwe,1908.0,44.15,0.262514,14.438802,1.166343,3130.0,0.000217,1.799678,NaN

#  Valeur manquantes : 
    Le ratio de proteines animales dans l'alimentation peut varier de 13% a 73%. Des valeurs manquantes dans les variable autres que 'pays'. le plus petit nombre de clés conserne une des variable les plus utiles: 'poulet_import_export'. Dans cette variable egalement, on observe des ecarts irregulier entre les quartiles.

In [26]:
df.describe(include = 'all')

,pays,dispo_calories,dispo_proteines,ratio_proteines_animales,population,population_croissance,pib,ppa,pib_croissance,poulet_import-export
count,238,173.000000,173.000000,173.000000,237.000000,230.000000,185.000000,185.000000,184.000000,116.000000
unique,238,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,2874.554913,82.075376,0.428036,38.357579,1.141948,20870.841622,0.031626,1.208318,inf
std,NaN,454.921695,20.754692,0.158920,161.816211,0.154193,22143.024374,0.121694,0.253684,NaN
min,NaN,1786.000000,42.410000,0.098749,0.000801,0.820026,761.500000,0.000005,0.493578,0.000000
25%,NaN,2563.000000,65.750000,0.286716,0.385637,1.040005,5028.900000,0.000225,1.044927,1.270636
50%,NaN,2857.000000,82.600000,0.442568,5.337962,1.118632,12864.600000,0.001667,1.171460,7.184890
75%,NaN,3277.000000,97.520000,0.559769,19.751466,1.232768,29711.900000,0.010694,1.339931,86.213926
max,NaN,3885.000000,146.130000,0.730880,1459.377612,1.936208,131908.000000,1.076570,2.056280,inf

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 238 entries, 0 to 237
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   pays                      238 non-null    object
 1   dispo_calories            173 non-null    float64
 2   dispo_proteines           173 non-null    float64
 3   ratio_proteines_animales  173 non-null    float64
 4   population                237 non-null    float64
 5   population_croissance     230 non-null    float64
 6   pib                       185 non-null    float64
 7   ppa                       185 non-null    float64
 8   pib_croissance            184 non-null    float64
 9   poulet_import-export      116 non-null    float64
dtypes: float64(9), object(1)
memory usage: 18.7+ KB

In [28]:
print(df[~df.index.isin(df.dropna().index)]['pays'].to_list())

['Albania', 'Algeria', 'American Samoa', 'Andorra', 'Angola', 'Anguilla', 'Aruba', 'Bahrain', 'Belize', 'Bermuda', 'Bhutan', 'Bonaire, Sint Eustatius and Saba', 'British Virgin Islands', 'Brunei Darussalam', 'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cameroon', 'Cayman Islands', 'Central African Republic', 'Chad', 'Channel Islands', 'China', 'China, Taiwan Province of', 'Comoros', 'Cook Islands', 'Cuba', 'Curaçao', "Democratic People's Republic of Korea", 'Democratic Republic of the Congo', 'Djibouti', 'Dominica', 'Ecuador', 'Equatorial Guinea', 'Eritrea', 'Ethiopia', 'Falkland Islands (Malvinas)', 'Faroe Islands', 'French Guyana', 'French Polynesia', 'Gabon', 'Gambia', 'Gibraltar', 'Greenland', 'Grenada', 'Guadeloupe', 'Guam', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Holy See', 'Iran (Islamic Republic of)', 'Isle of Man', 'Israel', 'Kiribati', "Lao People's Democratic Republic", 'Liberia', 'Libya', 'Liechtenstein', 'Madagascar', 'Malawi', 'Maldives', 'Mali', 'Marshall Islands', 'Martinique', 'Mauritania', 'Mauritius', 'Mayotte', 'Micronesia (Federated States of)', 'Monaco', 'Mongolia', 'Montserrat', 'Mozambique', 'Nauru', 'Nepal', 'Netherlands Antilles (former)', 'New Caledonia', 'New Zealand', 'Niue', 'Northern Mariana Islands', 'Palau', 'Palestine', 'Panama', 'Papua New Guinea', 'Paraguay', 'Puerto Rico', 'Qatar', 'Rwanda', 'Réunion', 'Saint Barthélemy', 'Saint Helena, Ascension and Tristan da Cunha', 'Saint Kitts and Nevis', 'Saint Lucia', 'Saint Pierre and Miquelon', 'Saint Vincent and the Grenadines', 'Saint-Martin (French part)', 'San Marino', 'Sao Tome and Principe', 'Seychelles', 'Sierra Leone', 'Singapore', 'Sint Maarten  (Dutch part)', 'Solomon Islands', 'Somalia', 'South Sudan', 'Sri Lanka', 'Sudan', 'Sudan (former)', 'Syrian Arab Republic', 'Tajikistan', 'Timor-Leste', 'Tokelau', 'Tonga', 'Turkmenistan', 'Turks and Caicos Islands', 'Tuvalu', 'United States Virgin Islands', 'Uzbekistan', 'Vanuatu', 'Venezuela (Bolivarian Republic of)', 'Viet Nam', 'Wallis and Futuna Islands', 'Western Sahara', 'Yemen', 'Zimbabwe']

In [30]:
df = df.replace([np.inf, -np.inf], np.nan).dropna().reset_index().drop(['index'], axis=1)
df.style.background_gradient(cmap='BrBG')

In [34]:
pip install geopandas

Collecting geopandas
  Using cached geopandas-0.10.2-py2.py3-none-any.whl (1.0 MB)
Collecting fiona>=1.8
  Using cached Fiona-1.8.20.tar.gz (1.3 MB)
  Using cached Fiona-1.8.19.tar.gz (1.3 MB)
  Using cached Fiona-1.8.18.tar.gz (1.3 MB)
  Using cached Fiona-1.8.17.tar.gz (1.3 MB)
  Using cached Fiona-1.8.16.tar.gz (1.3 MB)
  Using cached Fiona-1.8.15.tar.gz (1.3 MB)
  Using cached Fiona-1.8.14.tar.gz (1.3 MB)
  Using cached Fiona-1.8.13.post1.tar.gz (1.2 MB)
Note: you may need to restart the kernel to use updated packages.  Using cached Fiona-1.8.13.tar.gz (1.2 MB)
  Using cached Fiona-1.8.12.tar.gz (1.2 MB)
  Using cached Fiona-1.8.11.tar.gz (1.2 MB)
  Using cached Fiona-1.8.10.tar.gz (1.2 MB)
  Using cached Fiona-1.8.9.post2.tar.gz (1.2 MB)
  Using cached Fiona-1.8.9.post1.tar.gz (1.2 MB)
  Using cached Fiona-1.8.9.tar.gz (1.2 MB)
  Using cached Fiona-1.8.8.tar.gz (1.7 MB)
  Using cached Fiona-1.8.7.tar.gz (1.7 MB)
  Using cached Fiona-1.8.6.tar.gz (1.7 MB)

  Using cached Fiona-1.8.5.tar.gz (1.7 MB)
  Using cached Fiona-1.8.4.tar.gz (1.1 MB)
  Using cached Fiona-1.8.3.tar.gz (1.1 MB)
  Using cached Fiona-1.8.2.tar.gz (1.2 MB)
  Using cached Fiona-1.8.1.tar.gz (1.1 MB)
  Using cached Fiona-1.8.0.tar.gz (1.4 MB)
Collecting geopandas
  Using cached geopandas-0.10.1-py2.py3-none-any.whl (1.0 MB)
  Using cached geopandas-0.10.0-py2.py3-none-any.whl (1.0 MB)
  Using cached geopandas-0.9.0-py2.py3-none-any.whl (994 kB)
Requirement already satisfied: shapely>=1.6 in c:\users\zolboy\anaconda3\lib\site-packages (from geopandas) (1.8.0)
  Using cached geopandas-0.8.2-py2.py3-none-any.whl (962 kB)
Collecting fiona
  Using cached Fiona-1.7.13.tar.gz (731 kB)
Requirement already satisfied: pandas>=0.23.0 in c:\users\zolboy\anaconda3\lib\site-packages (from geopandas) (1.3.4)
Requirement already satisfied: pyproj>=2.2.0 in c:\users\zolboy\anaconda3\lib\site-packages (from geopandas) (3.3.0)
Requirement already satisfied: pytz>=2017.3 in c:\users\zolboy\anaconda3\lib\site-packages (from pandas>=0.23.0->geopandas) (2021.3)
Requirement already satisfied: numpy>=1.17.3 in c:\users\zolboy\anaconda3\lib\site-packages (from pandas>=0.23.0->geopandas) (1.20.3)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\zolboy\anaconda3\lib\site-packages (from pandas>=0.23.0->geopandas) (2.8.2)
Requirement already satisfied: certifi in c:\users\zolboy\anaconda3\lib\site-packages (from pyproj>=2.2.0->geopandas) (2021.10.8)
Requirement already satisfied: six>=1.5 in c:\users\zolboy\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas>=0.23.0->geopandas) (1.16.0)
Requirement already satisfied: cligj>=0.4 in c:\users\zolboy\anaconda3\lib\site-packages (from fiona->geopandas) (0.7.2)
Requirement already satisfied: click-plugins in c:\users\zolboy\anaconda3\lib\site-packages (from fiona->geopandas) (1.1.1)
Requirement already satisfied: munch in c:\users\zolboy\anaconda3\lib\site-packages (from fiona->geopandas) (2.5.0)
Requirement already satisfied: click>=4.0 in c:\users\zolboy\anaconda3\lib\site-packages (from cligj>=0.4->fiona->geopandas) (8.0.3)
Requirement already satisfied: colorama in c:\users\zolboy\anaconda3\lib\site-packages (from click>=4.0->cligj>=0.4->fiona->geopandas) (0.4.4)
Building wheels for collected packages: fiona
  Building wheel for fiona (setup.py): started
  Building wheel for fiona (setup.py): finished with status 'error'
  Running setup.py clean for fiona
Failed to build fiona
Installing collected packages: fiona, geopandas
    Running setup.py install for fiona: started
    Running setup.py install for fiona: finished with status 'error'

    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\zolboy\anaconda3\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\zolboy\\AppData\\Local\\Temp\\pip-install-hfakpalh\\fiona_bfb4ed30c5bd4efeba26faf0e4e9385b\\setup.py'"'"'; __file__='"'"'C:\\Users\\zolboy\\AppData\\Local\\Temp\\pip-install-hfakpalh\\fiona_bfb4ed30c5bd4efeba26faf0e4e9385b\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\zolboy\AppData\Local\Temp\pip-pip-egg-info-1lipclhb'
         cwd: C:\Users\zolboy\AppData\Local\Temp\pip-install-hfakpalh\fiona_bfb4ed30c5bd4efeba26faf0e4e9385b\
    Complete output (1 lines):
    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/ec/f7/093890341a7e8fbfcdfa04caf4dfb588ebab32c13ceaa6a3819da79ea106/Fiona-1.8.20.tar.gz#sha256=a70502d2857b82f749c09cb0dea3726787747933a2a1599b5ab787d74e3c143b (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\zolboy\anaconda3\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\zolboy\\AppData\\Local\\Temp\\pip-install-hfakpalh\\fiona_73e8ff8aac5847fb9d2e9634fb2cba97\\setup.py'"'"'; __file__='"'"'C:\\Users\\zolboy\\AppData\\Local\\Temp\\pip-install-hfakpalh\\fiona_73e8ff8aac5847fb9d2e9634fb2cba97\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\zolboy\AppData\Local\Temp\pip-pip-egg-info-57au06hm'
         cwd: C:\Users\zolboy\AppData\Local\Temp\pip-install-hfakpalh\fiona_73e8ff8aac5847fb9d2e9634fb2cba97\
    Complete output (1 lines):
    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/a0/d9/6042aeb073d11341f7726de0586ff71c13117c34959dcf07bd4ee6d4b93e/Fiona-1.8.19.tar.gz#sha256=b9059e0b29c2e9e6b817e53f941e77e1aca7075f986005d38db307067b60458f (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\zolboy\anaconda3\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\zolboy\\AppData\\Local\\Temp\\pip-install-hfakpalh\\fiona_759502e15e4d42eb99a685763f5c622f\\setup.py'"'"'; __file__='"'"'C:\\Users\\zolboy\\AppData\\Local\\Temp\\pip-install-hfakpalh\\fiona_759502e15e4d42eb99a685763f5c622f\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\zolboy\AppData\Local\Temp\pip-pip-egg-info-dymaawr9'
         cwd: C:\Users\zolboy\AppData\Local\Temp\pip-install-hfakpalh\fiona_759502e15e4d42eb99a685763f5c622f\
    Complete output (1 lines):
    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/9f/e8/401cdaa58d862a25c4b3365acf7d2bd7ac77191e3dc9acdcdac0eff20ff0/Fiona-1.8.18.tar.gz#sha256=b732ece0ff8886a29c439723a3e1fc382718804bb057519d537a81308854967a (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\zolboy\anaconda3\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\zolboy\\AppData\\Local\\Temp\\pip-install-hfakpalh\\fiona_dbfdcc4353804866bbae1326a07aa226\\setup.py'"'"'; __file__='"'"'C:\\Users\\zolboy\\AppData\\Local\\Temp\\pip-install-hfakpalh\\fiona_dbfdcc4353804866bbae1326a07aa226\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\zolboy\AppData\Local\Temp\pip-pip-egg-info-_037086f'
         cwd: C:\Users\zolboy\AppData\Local\Temp\pip-install-hfakpalh\fiona_dbfdcc4353804866bbae1326a07aa226\
    Complete output (1 lines):
    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/88/62/69347ba2c41b526e1953c4cb66d51170b2869808863c03af202ba0121670/Fiona-1.8.17.tar.gz#sha256=716201c21246587f374785bec6d6a20a984fe1f6c2b0e83bf15127eb8f724d0c (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\zolboy\anaconda3\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\zolboy\\AppData\\Local\\Temp\\pip-install-hfakpalh\\fiona_ff4fb2f7ae184d959cb0cf17466f668c\\setup.py'"'"'; __file__='"'"'C:\\Users\\zolboy\\AppData\\Local\\Temp\\pip-install-hfakpalh\\fiona_ff4fb2f7ae184d959cb0cf17466f668c\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\zolboy\AppData\Local\Temp\pip-pip-egg-info-_q6mbevp'
         cwd: C:\Users\zolboy\AppData\Local\Temp\pip-install-hfakpalh\fiona_ff4fb2f7ae184d959cb0cf17466f668c\
    Complete output (1 lines):
    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/1e/60/dfc6115a11338d8aa96cacd8c60635223d9c97d61d556c90acc5dfd663fa/Fiona-1.8.16.tar.gz#sha256=fd6dfb65959becc916e9f6928618bfd59c16cdbc413ece0fbac61489cd11255f (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\zolboy\anaconda3\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\zolboy\\AppData\\Local\\Temp\\pip-install-hfakpalh\\fiona_fcb96a147ad7450b9be7e702d8fe5919\\setup.py'"'"'; __file__='"'"'C:\\Users\\zolboy\\AppData\\Local\\Temp\\pip-install-hfakpalh\\fiona_fcb96a147ad7450b9be7e702d8fe5919\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\zolboy\AppData\Local\Temp\pip-pip-egg-info-eaqivzyn'
         cwd: C:\Users\zolboy\AppData\Local\Temp\pip-install-hfakpalh\fiona_fcb96a147ad7450b9be7e702d8fe5919\
    Complete output (1 lines):
    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/55/2f/17450ec2c8fcc720a8a3e4d9a383499508475c7cfb90f7eca9fb585ac598/Fiona-1.8.15.tar.gz#sha256=3b1c9b5c834fae2fe947cfaea176db890bc6750d1a6ba9f54d969c19ffcd191e (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\zolboy\anaconda3\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\zolboy\\AppData\\Local\\Temp\\pip-install-hfakpalh\\fiona_70b29c526e5f4445aaa26ba3a710493a\\setup.py'"'"'; __file__='"'"'C:\\Users\\zolboy\\AppData\\Local\\Temp\\pip-install-hfakpalh\\fiona_70b29c526e5f4445aaa26ba3a710493a\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\zolboy\AppData\Local\Temp\pip-pip-egg-info-t0vjussv'
         cwd: C:\Users\zolboy\AppData\Local\Temp\pip-install-hfakpalh\fiona_70b29c526e5f4445aaa26ba3a710493a\
    Complete output (1 lines):
    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/5c/fd/5ec54f2d9b3d5dd23dd443fad5630d6b872e2664814c68b856c47e0d65af/Fiona-1.8.14.tar.gz#sha256=6eac038206c89d2cf5f99ea38b81cc228dc21eac5f47870a9a32d453b0007f4d (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\zolboy\anaconda3\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\zolboy\\AppData\\Local\\Temp\\pip-install-hfakpalh\\fiona_17bad5afe2d34bd0bf9a44c2bdfde01e\\setup.py'"'"'; __file__='"'"'C:\\Users\\zolboy\\AppData\\Local\\Temp\\pip-install-hfakpalh\\fiona_17bad5afe2d34bd0bf9a44c2bdfde01e\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\zolboy\AppData\Local\Temp\pip-pip-egg-info-6pnsbc89'
         cwd: C:\Users\zolboy\AppData\Local\Temp\pip-install-hfakpalh\fiona_17bad5afe2d34bd0bf9a44c2bdfde01e\
    Complete output (1 lines):
    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/6d/42/f4a7cac53b28fa70e9a93d0e89a24d33e14826dad6644b699362ad84dde0/Fiona-1.8.13.post1.tar.gz#sha256=1a432bf9fd56f089256c010da009c90d4a795c531a848132c965052185336600 (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\zolboy\anaconda3\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\zolboy\\AppData\\Local\\Temp\\pip-install-hfakpalh\\fiona_66dd121d01ba4294b38018b3e86b2b8f\\setup.py'"'"'; __file__='"'"'C:\\Users\\zolboy\\AppData\\Local\\Temp\\pip-install-hfakpalh\\fiona_66dd121d01ba4294b38018b3e86b2b8f\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\zolboy\AppData\Local\Temp\pip-pip-egg-info-r8unzpct'
         cwd: C:\Users\zolboy\AppData\Local\Temp\pip-install-hfakpalh\fiona_66dd121d01ba4294b38018b3e86b2b8f\
    Complete output (1 lines):
    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/be/04/31d0a6f03943b1684f32c9b861be40c1fd282468fa6bd54ddf4a774e6b0f/Fiona-1.8.13.tar.gz#sha256=5ec34898c8b983a723fb4e949dd3e0ed7e691c303e51f6bfd61e52ac9ac813ae (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\zolboy\anaconda3\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\zolboy\\AppData\\Local\\Temp\\pip-install-hfakpalh\\fiona_2f8fd680724f43f08940465073796622\\setup.py'"'"'; __file__='"'"'C:\\Users\\zolboy\\AppData\\Local\\Temp\\pip-install-hfakpalh\\fiona_2f8fd680724f43f08940465073796622\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\zolboy\AppData\Local\Temp\pip-pip-egg-info-i586917e'
         cwd: C:\Users\zolboy\AppData\Local\Temp\pip-install-hfakpalh\fiona_2f8fd680724f43f08940465073796622\
    Complete output (1 lines):
    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/97/d8/feab39987296437fbdc3029fb39752a14355d217d73b93471010b8dd63a3/Fiona-1.8.12.tar.gz#sha256=c9266ddf6ae2a64fcea20014ddf27f800ac07584f2fdb09c2a02f3b3a52e371c (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\zolboy\anaconda3\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\zolboy\\AppData\\Local\\Temp\\pip-install-hfakpalh\\fiona_f2fefc1ac6864c39b5813801c18f7e60\\setup.py'"'"'; __file__='"'"'C:\\Users\\zolboy\\AppData\\Local\\Temp\\pip-install-hfakpalh\\fiona_f2fefc1ac6864c39b5813801c18f7e60\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\zolboy\AppData\Local\Temp\pip-pip-egg-info-ta6mdz94'
         cwd: C:\Users\zolboy\AppData\Local\Temp\pip-install-hfakpalh\fiona_f2fefc1ac6864c39b5813801c18f7e60\
    Complete output (1 lines):
    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/9d/f4/0a0ddc6174c4a93679b5f1dd3535e7ef8989828e6d5f86112de681f8c87b/Fiona-1.8.11.tar.gz#sha256=1e7ca9e051f5bffa1c43c70d573da9ca223fc076b84fa73380614fc02b9eb7f6 (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\zolboy\anaconda3\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\zolboy\\AppData\\Local\\Temp\\pip-install-hfakpalh\\fiona_6814b890b4514d058097df935eae6a34\\setup.py'"'"'; __file__='"'"'C:\\Users\\zolboy\\AppData\\Local\\Temp\\pip-install-hfakpalh\\fiona_6814b890b4514d058097df935eae6a34\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\zolboy\AppData\Local\Temp\pip-pip-egg-info-veiizoji'
         cwd: C:\Users\zolboy\AppData\Local\Temp\pip-install-hfakpalh\fiona_6814b890b4514d058097df935eae6a34\
    Complete output (1 lines):
    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/13/73/f80b491ed8559326fab202a6d6333a3cd6e8be1e9d782bc6c0d03d476457/Fiona-1.8.10.tar.gz#sha256=ff562eb2f3960e21f8c7f050ddd7f47a763869ea14afc2234a40df72666c6a2c (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\zolboy\anaconda3\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\zolboy\\AppData\\Local\\Temp\\pip-install-hfakpalh\\fiona_ddbb480ab98a4b9c9371c1b103a1fccf\\setup.py'"'"'; __file__='"'"'C:\\Users\\zolboy\\AppData\\Local\\Temp\\pip-install-hfakpalh\\fiona_ddbb480ab98a4b9c9371c1b103a1fccf\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\zolboy\AppData\Local\Temp\pip-pip-egg-info-l1vf92yi'
         cwd: C:\Users\zolboy\AppData\Local\Temp\pip-install-hfakpalh\fiona_ddbb480ab98a4b9c9371c1b103a1fccf\
    Complete output (1 lines):
    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/9b/52/45e75507660ce0e86176d0f59b659560f687e2c7e9ebf82a10e7dcd2d3b7/Fiona-1.8.9.post2.tar.gz#sha256=210fb038b579fab38f35ddbdd31b9725f4d5099b3edfd4b87c983e5d47b79983 (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\zolboy\anaconda3\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\zolboy\\AppData\\Local\\Temp\\pip-install-hfakpalh\\fiona_eb5fd8096b9f4aa7ac16704351962fa4\\setup.py'"'"'; __file__='"'"'C:\\Users\\zolboy\\AppData\\Local\\Temp\\pip-install-hfakpalh\\fiona_eb5fd8096b9f4aa7ac16704351962fa4\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\zolboy\AppData\Local\Temp\pip-pip-egg-info-4cdr8auv'
         cwd: C:\Users\zolboy\AppData\Local\Temp\pip-install-hfakpalh\fiona_eb5fd8096b9f4aa7ac16704351962fa4\
    Complete output (1 lines):

In [ ]:
import geopandas as gpd
import geoplot

# Dataset naturalearth_lowres
world = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres')).drop(['pop_est', 'gdp_md_est'], axis=1)
world.rename(columns={'name': 'pays'}, inplace=True)

# Harmonisation des noms de pays entre les 2 dataframes
world = world.replace('Russia', 'Russian Federation')
world = world.replace('United Kingdom', 'United Kingdom of Great Britain and Northern Ireland')
world = world.replace('Dominican Rep.', 'Dominican Republic')
world = world.replace('Bolivia', 'Bolivia (Plurinational State of)')
world = world.replace('Bosnia and Herz.', 'Bosnia and Herzegovina')
world = world.replace('South Korea', 'Republic of Korea')
world = world.replace('Macedonia', 'North Macedonia')
world = world.replace('China', 'China, mainland')
world = world.replace('Tanzania', 'United Republic of Tanzania')
world = world.replace('eSwatini', 'Eswatini')
world